services:
  app:
    build: .
    ports:
      - "8224:3000"
    volumes:
      - .:/app
    environment:
      # Corrigido para apontar para a porta padrão do Postgres
      DATABASE_URL: postgres://victorsoaresho:senha@db:5432/launchstore
    depends_on:
      - db
    # O comando principal será o CMD do Dockerfile (npm start)

  db:
    image: postgres:15
    restart: always
    # Removido comando que alterava a porta interna
    environment:
      POSTGRES_USER: victorsoaresho
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: launchstore
    ports:
      # Mapeamento corrigido e único: porta 8225 do host para 5432 do container
      - "8225:5432"
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql:ro