name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/provavollo:latest # Nome da imagem consistente

  deploy-application:
    needs: build-and-push # Depende do sucesso do build e push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3 # Necessário para pegar o docker-compose.yml

      - name: Copiar docker-compose.yml para servidor remoto
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml" # Certifique-se que este yml usa a imagem correta
          target: "~/app"
          strip_components: 0 # Copia o arquivo diretamente para dentro de ~/app

      - name: Deploy usando docker-compose no servidor remoto
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            echo "Parando e removendo contêineres antigos..."
            docker compose down --remove-orphans || true
            echo "Puxando nova imagem do Docker Hub..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/provavollo:latest # Puxa a imagem correta
            echo "Iniciando novos contêineres com Docker Compose..."
            docker compose up -d --build # --build pode ser opcional se o compose.yml só referencia a imagem
            echo "Deploy concluído."