name: Pipeline de CI/CD

on:
  push:
    branches:
      - main

jobs:
  construir-e-enviar-imagem:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e enviar imagem Docker (Aplicação)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/launchstore_app:latest

  fazer-deploy-aplicacao:
    needs: construir-e-enviar-imagem
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Copiar database.sql para o servidor remoto
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./database.sql"
          target: "~/launchstore/"
          strip_components: 0

      - name: Conectar ao servidor remoto e fazer deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKERHUB_USERNAME
          script: |
            echo "Parando e removendo contêineres antigos (se houver)..."
            docker stop launchstore_app || true
            docker rm launchstore_app || true
            docker stop launchstore_db || true
            docker rm launchstore_db || true

            echo "Removendo rede Docker antiga (se houver)..."
            docker network rm launchstore-network || true

            echo "Criando nova rede Docker..."
            docker network create launchstore-network

            echo "Iniciando o contêiner do PostgreSQL..."
            docker run -d \
              --name launchstore_db \
              --network launchstore-network \
              -p 8225:5432 \
              -e POSTGRES_USER=victorsoaresho \
              -e POSTGRES_PASSWORD=senha \
              -e POSTGRES_DB=launchstore \
              -v pgdata:/var/lib/postgresql/data \
              postgres:15

            echo "Aguardando o PostgreSQL iniciar..."
            sleep 10

            echo "Baixando a nova imagem da aplicação do Docker Hub..."
            docker pull victorsoaresho/launchstore_app:latest

            echo "Inicializando o contêiner da aplicação..."
            docker run -d \
              --name launchstore_app \
              --network launchstore-network \
              -p 8224:8224 \
              victorsoaresho/launchstore_app:latest

            echo "Executando o script database.sql a partir da imagem da aplicação..."
            docker exec -u postgres launchstore_db psql -d launchstore -f /app/database.sql

            echo "Deploy finalizado com sucesso."