name: Pipeline de CI/CD

on:
  push:
    branches:
      - main

jobs:
  construir-e-enviar-imagem:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir e enviar imagem Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/provavollo:latest

  fazer-deploy-aplicacao:
    needs: construir-e-enviar-imagem
    runs-on: ubuntu-latest
    steps:
      - name: Baixar código do repositório
        uses: actions/checkout@v3

      - name: Copiar docker-compose.yml para o servidor remoto
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "~/launchstore"
          strip_components: 0

      - name: Executar análise com SonarQube no servidor remoto
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Iniciando container do SonarQube..."
            docker run -d --name sonarqube -p 8221:9000 sonarqube

            echo "Aguardando o SonarQube inicializar (45s)..."
            sleep 45
            cd ~/launchstore/app
            sonar-scanner \
              -Dsonar.projectKey=victorsoaresho_continues-integrations-workflow \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:8221 \
              -Dsonar.login=51fc345ffb4e5b35948f1150f4c4c5b7d18013f6

            echo "Encerrando container do SonarQube..."
            docker stop sonarqube && docker rm sonarqube

      - name: Fazer deploy com Docker Compose no servidor remoto
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKERHUB_USERNAME
          script: |
            echo "Acessando diretório da aplicação..."
            cd ~/launchstore

            echo "Parando e removendo contêineres antigos (se houver)..."
            docker compose down --remove-orphans || true

            echo "Baixando a nova imagem do Docker Hub..."
            docker pull victorsoaresho/provavollo:latest

            echo "Extraindo arquivos da nova imagem para ~/launchstore..."
            container_id=$(docker create victorsoaresho/provavollo:latest)
            docker cp "$container_id":/app ./
            docker rm "$container_id"

            echo "Inicializando os novos contêineres com Docker Compose..."
            cd app/
            docker compose up -d --build

            echo "Deploy finalizado com sucesso."
