name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/provavollo:latest

  deploy-application:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy docker-compose.yml to remote server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "./docker-compose.yml"
          target: "~/launchstore"
          strip_components: 0

      - name: Executar análise SonarQube no servidor remoto
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Subindo container do SonarQube..."
            docker run -d --name sonarqube -p 8221:9000 sonarqube

            echo "Aguardando o SonarQube iniciar..."
            sleep 45
            cd ~/launchstore/app
            sonar-scanner \
              -Dsonar.projectKey=victorsoaresho_continues-integrations-workflow \
              -Dsonar.sources=. \
              -Dsonar.host.url=http://localhost:8221 \
              -Dsonar.login=51fc345ffb4e5b35948f1150f4c4c5b7d18013f6

            echo "Parando o container do SonarQube..."
            docker stop sonarqube && docker rm sonarqube

      - name: Deploy with Docker Compose on remote server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 201.23.3.86
          username: aluno
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKERHUB_USERNAME
          script: |
            echo "Acessando pasta de trabalho..."
            cd ~/launchstore

            echo "Parando e removendo contêineres antigos..."
            docker compose down --remove-orphans || true

            echo "Puxando nova imagem do Docker Hub..."
            docker pull victorsoaresho/provavollo:latest

            echo "Extraindo arquivos da imagem para ~/launchstore..."
            container_id=$(docker create victorsoaresho/provavollo:latest)
            docker cp "$container_id":/app ./
            docker rm "$container_id"

            echo "Iniciando novos contêineres com Docker Compose..."
            cd app/
            docker compose up -d --build

            echo "Deploy concluído."
